---
title: "Proyecto Final"
author: "Guillermo Puente/Fausto Holcombe"
date: "6 de noviembre de 2019"
output: rmarkdown::github_document
---



#Librerías
```{r, cache=TRUE1}

library(readxl)
library(readr)
library(plotly)
library(tidyr)
library(dplyr)
library(DataExplorer)
library(lubridate)
library(stringr)
library(zoo)
library(ggplot2)
library(corrplot)
```



#Funciones
```{r, cache=TRUE}

#Función para arreglar las tablas a la hora de importar#
import_xl_double_header <- function(file,start_column = 2,start_row = 9,no_upper_col_num, col_num){
  xl <- read_xlsx(file, range = cell_limits(c(start_row,start_column), c(NA,start_column + col_num - 1)))
  upper_col_names <- names(xl)
  lower_col_names <- as.character(as.vector(xl[1,]))
  upper_col_names[str_detect(upper_col_names,"^\\.\\.\\.[0-9]+")] <- NA
  if(is.na(upper_col_names[1])){
    upper_col_names[1] <-""
  }
  upper_col_names <- na.locf(upper_col_names)
  if(length(no_upper_col_num) == 1 & no_upper_col_num[1] == 0){
    upper_col_names[1:length(upper_col_names)] <- ""
    final_col_names <- paste0(upper_col_names,lower_col_names)
  } else {
    upper_col_names[no_upper_col_num] <- ""
    final_col_names <- c()
    for(n in 1:col_num){
      if(upper_col_names[n] == ""){
        final_col_names <- c(final_col_names,paste0(upper_col_names[n],lower_col_names[n]))
      } else {
        final_col_names <- c(final_col_names,paste(upper_col_names[n],lower_col_names[n], sep = ":"))
      }
    }
  }
  xl <- tail(xl,-1)
  names(xl) <- final_col_names
  return(xl)
}

#Limpieza de la fila total#
total_line_clean <- function(df){
  if(tail(df,1)[[1]] == "TOTAL"){
    df <- head(df, -1)
    return(df)
  } else {
    return(df)
  }
}

#Función para agregarle nombre a columnas específicas
sup_column_name <- function(df, cols_change , sup_col_name){
  names(df)[cols_change] <- paste(sup_col_name,names(df[cols_change]),sep = ":")
  return(df)
}


split_inner_function <- function(df, side, micro){
  if(str_detect(df[3],":")){
    split_char <- str_locate(df[3],":")[1]
    if(side == "right"){
      minor_cat <- substring(df[3],split_char+1)
      return(minor_cat)
    } else if(side == "left"){
      major_cat <- substring(df[3],1,split_char-1)
      return(major_cat)
    }
  } else if(micro != TRUE){
    return(df[3])
  } else {
    return("No hay grupo")
  }
}

split_outer_function <- function(df){
  new_df <- df
  new_df$caracteristica <- apply(new_df,1,split_inner_function, side = "left", micro = FALSE)
  new_df$grupo <- apply(new_df,1,split_inner_function, side = "right", micro = TRUE)
  new_df <- subset(new_df, select = -c(categoria))
  new_df <- new_df %>% select(1,2,4,5,3)
  new_df[[5]] <- as.numeric(new_df[[5]])
  return(new_df)
}

separate_id <- function(df, side){
  if(length(df[1]) == 4){
    if(side == "left"){
      return(substring(df[1],1,2))
    } else if(side == "right"){
      return(substring(df[1],3,4))
    }
  } else if(length(df[1] == 3)){
    if(side == "left"){
      return(substring(df[1],1,1))
    } else if(side == "right"){
      return(substring(df[1],2,3))
    }
  }
}

separate_id_outer <- function(df){
  new_df <- df
  new_df$departamento <- apply(new_df,1,separate_id, side = "left")
  new_df$municipio <- apply(new_df,1,separate_id, side = "right")
  new_df <- subset(new_df, select = -c(`Código`))
  new_df <- new_df %>% select(5,6,1,2,3,4)
}

define_region <- function(df){
  if(df[1] %in% c(1)){
    return("Metropolitana")
  } else if(df[1] %in% c(15,16)){
    return("Norte")
  } else if(df[1] %in% c(20,2,18,19)){
    return("Nororiente")
  } else if(df[1] %in% c(22,21,6)){
    return("Suroriente")
  } else if(df[1] %in% c(4,3,5)){
    return("Central")
  } else if(df[1] %in% c(9,11,12,10,7,8)){
    return("Suroccidente")
  } else if(df[1] %in% c(13,14)){
    return("Noroccidente")
  } else {
    return("Petén")
  }
}

plot_barcharts <- function(df){
  categorias <- unique(df$caracteristica)
  if(names(df)[[1]] == "departamento"){
    graph_df <-  df %>% inner_join(tabla_dep, by = c("departamento" = "codigo_dep"))
  } else if(names(df)[[1]] == "Código"){
    graph_df <-  df %>% inner_join(tabla_dep, by = c("Código" = "codigo_dep"))
  }
  for(x in categorias){
    new_graph_df <- graph_df %>% filter(caracteristica == x) %>% group_by(region,grupo) %>% summarise(observaciones_totales = sum(observaciones)) %>% inner_join(tabla_pob_region, by = c("region")) %>% mutate(observaciones_normalizadas = observaciones_totales/porcentaje_total)
    if(sum(str_detect(new_graph_df$grupo,"No hay grupo")) == 0){
      print(ggplot(new_graph_df, aes(region,observaciones_normalizadas)) 
            + geom_bar(stat = "identity", aes(fill = grupo), position = "dodge")
            + xlab("Region") + ylab("Observaciones") + ggtitle(paste(x,"por region")))
      } else {
        new_graph_df <- new_graph_df %>% subset(select = -c(grupo))
        print(ggplot(new_graph_df, aes(region,observaciones_normalizadas))
              + geom_bar(stat = "identity", fill = "steelblue", position = "dodge")
            + xlab("Region") + ylab("Observaciones") + ggtitle(paste(x,"por region")))
    }
  }
}


plot_barcharts_hog <- function(df){
  categorias <- unique(df$caracteristica)
  if(names(df)[[1]] == "departamento"){
    graph_df <-  df %>% inner_join(tabla_dep, by = c("departamento" = "codigo_dep"))
  } else if(names(df)[[1]] == "Código"){
    graph_df <-  df %>% inner_join(tabla_dep, by = c("Código" = "codigo_dep"))
  }
  for(x in categorias){
    new_graph_df <- graph_df %>% filter(caracteristica == x) %>% group_by(region,grupo) %>% summarise(observaciones_totales = mean(observaciones))
    if(sum(str_detect(new_graph_df$grupo,"No hay grupo")) == 0){
      print(ggplot(new_graph_df, aes(region,observaciones_totales)) 
            + geom_bar(stat = "identity", aes(fill = grupo), position = "dodge")
            + xlab("Region") + ylab("Observaciones") + ggtitle(paste(x,"por region")))
      } else {
        new_graph_df <- new_graph_df %>% subset(select = -c(grupo))
        print(ggplot(new_graph_df, aes(region,observaciones_totales))
              + geom_bar(stat = "identity", fill = "steelblue", position = "dodge")
            + xlab("Region") + ylab("Observaciones") + ggtitle(paste(x,"por region")))
    }
  }
}


plot_barcharts_norm_viv <- function(df){
  categorias <- unique(df$caracteristica)
  if(names(df)[[1]] == "departamento"){
    graph_df <-  df %>% inner_join(tabla_dep, by = c("departamento" = "codigo_dep"))
  } else if(names(df)[[1]] == "Código"){
    graph_df <-  df %>% inner_join(tabla_dep, by = c("Código" = "codigo_dep"))
  }
  for(x in categorias){
    new_graph_df <- graph_df %>% filter(caracteristica == x) %>% group_by(region,grupo) %>% summarise(observaciones_totales = sum(observaciones)) %>% inner_join(tabla_viv_region, by = c("region")) %>% mutate(observaciones_normalizadas = observaciones_totales/porcentaje_total)
    if(sum(str_detect(new_graph_df$grupo,"No hay grupo")) == 0){
      print(ggplot(new_graph_df, aes(region,observaciones_normalizadas)) 
            + geom_bar(stat = "identity", aes(fill = grupo), position = "dodge")
            + xlab("Region") + ylab("Observaciones") + ggtitle(paste(x,"por region")))
      } else {
        new_graph_df <- new_graph_df %>% subset(select = -c(grupo))
        print(ggplot(new_graph_df, aes(region,observaciones_normalizadas))
              + geom_bar(stat = "identity", fill = "steelblue", position = "dodge")
            + xlab("Region") + ylab("Observaciones") + ggtitle(paste(x,"por region")))
    }
  }
}

split_corr_plot <- function(df, split_size, splits){
  for(x in 1:splits){
    if(x == 1){
      corr_df <- df[2:as.numeric(1+split_size)]
      (plot_correlation(na.omit(corr_df)))
    } else if(x > 1){
      corr_df <- df[as.numeric(1+split_size*(x-1)):as.numeric(1+split_size*x)]
      (plot_correlation(na.omit(corr_df)))
    }
  }
}
```



#Importación de Tablas
```{r, cache=TRUE}

#Importación de tablas con las filas y columnas correctas#
car_dep <- import_xl_double_header('caracteristicas_departamental.xlsx', no_upper_col_num = c(1,2,3,13,32), col_num = 45)
car_mun <- import_xl_double_header('caracteristicas_municipal.xlsx', no_upper_col_num = c(1,2,3,13,32), col_num = 45)
edu_dep <- import_xl_double_header('educacion_departamental.xlsx', no_upper_col_num = c(1,2,21), col_num = 29)
edu_mun <- import_xl_double_header('educacion_municipal.xlsx', no_upper_col_num = c(0), col_num = 29)
emp_dep <- import_xl_double_header('empleo_departamental.xlsx', no_upper_col_num = c(0), col_num = 9)
emp_mun <- import_xl_double_header('empleo_municipal.xlsx', no_upper_col_num = c(0), col_num = 9)
hog_dep <- import_xl_double_header('hogares_departamental.xlsx', no_upper_col_num = c(0), col_num = 6)
hog_mun <- import_xl_double_header('hogares_municipal.xlsx', no_upper_col_num = c(0), col_num = 6)
pob_dep <- import_xl_double_header('poblacion_departamental.xlsx', no_upper_col_num = c(1,2,3,4,5,6,7,8,9,10,32,33,45,46,47,48,49,50,51,52), col_num = 52)
pob_mun <- import_xl_double_header('poblacion_municipal.xlsx', no_upper_col_num = c(1,2,3,4,5,6,7,8,9,10,32,33,45,46,47,48,49,50,51,52), col_num = 52)
tec_dep <- import_xl_double_header('tecnologia_departamental.xlsx', no_upper_col_num = c(0), col_num = 16)
tec_mun <- import_xl_double_header('tecnologia_municipal.xlsx', no_upper_col_num = c(0), col_num = 16)
viv_dep <- import_xl_double_header('vivienda_departamental.xlsx', no_upper_col_num = c(1,2,3,4,5), col_num = 43)
viv_mun <- import_xl_double_header('vivienda_municipal.xlsx', no_upper_col_num = c(0), col_num = 43)
pue_dep <- import_xl_double_header('pueblo_departamental.xlsx', no_upper_col_num = c(1,2,3,61), col_num = 61)

#Eliminación de la fila total#
car_dep <- total_line_clean(car_dep)
car_mun <- total_line_clean(car_mun)
edu_dep <- total_line_clean(edu_dep)
edu_mun <- total_line_clean(edu_mun)
emp_dep <- total_line_clean(emp_dep)
emp_mun <- total_line_clean(emp_mun)
hog_dep <- total_line_clean(hog_dep)
hog_mun <- total_line_clean(hog_mun)
pob_dep <- total_line_clean(pob_dep)
pob_mun <- total_line_clean(pob_mun)
tec_dep <- total_line_clean(tec_dep)
tec_mun <- total_line_clean(tec_mun)
viv_dep <- total_line_clean(viv_dep)
viv_mun <- total_line_clean(viv_mun)
pue_dep <- total_line_clean(pue_dep)


```



#Tidy
```{r, cache=TRUE}

#Arreglo de los nombres repetidos dentro de las tablas
viv_mun <- sup_column_name(viv_mun, cols_change =  c(6:11), sup_col_name = "Tipo de Casa")
viv_mun <- sup_column_name(viv_mun, cols_change =  c(17:27), sup_col_name = "Tipo de Pared")
viv_mun <- sup_column_name(viv_mun, cols_change =  c(28:36), sup_col_name = "Tipo de Techo")
viv_mun <- sup_column_name(viv_mun, cols_change =  c(37:43), sup_col_name = "Tipo de Piso")

edu_mun <- sup_column_name(edu_mun, cols_change =  c(3:11), sup_col_name = "Nivel de Estudio")
edu_mun <- sup_column_name(edu_mun, cols_change =  c(12:20), sup_col_name = "Razon de No Estudiar")

tec_dep <- sup_column_name(tec_dep, cols_change =  c(4:6), sup_col_name = "Uso de Celular")
tec_dep <- sup_column_name(tec_dep, cols_change =  c(7:9), sup_col_name = "Uso de Computadora")
tec_dep <- sup_column_name(tec_dep, cols_change =  c(10:12), sup_col_name = "Uso de Internet")

tec_mun <- sup_column_name(tec_mun, cols_change =  c(4:6), sup_col_name = "Uso de Celular")
tec_mun <- sup_column_name(tec_mun, cols_change =  c(7:9), sup_col_name = "Uso de Computadora")
tec_mun <- sup_column_name(tec_mun, cols_change =  c(10:12), sup_col_name = "Uso de Internet")

#definir tablas para correlaciones
car_dep_corr <- car_dep %>% select(1,33:39)
edu_dep_corr <- edu_dep %>% select(1,3:20)
emp_dep_corr <- emp_dep %>% select(1,4,6,7)
pob_dep_corr <- pob_dep %>% select(1,6,8)
tec_dep_corr <- tec_dep[c(1,4,5,7,8,10,11,13:16)]
tabla_correlaciones <- car_dep_corr %>% inner_join(edu_dep_corr, by = c("Código")) %>% inner_join(emp_dep_corr, by = c("Código")) %>% inner_join(pob_dep_corr, by = c("Código")) %>% inner_join(tec_dep_corr, by = c("Código"))
tabla_correlaciones[] <- lapply(tabla_correlaciones, function(x) as.numeric(as.character(x)))

#gather de las tablas para tener sólamente columnas de Código, departamento, categoría y observaciones
car_dep <- gather(car_dep,categoria,observaciones,-c(`Código`,Departamento))
car_mun <- gather(car_mun,categoria,observaciones,-c(`Código`,Municipio))
edu_dep <- gather(edu_dep,categoria,observaciones,-c(`Código`,Departamento))
edu_mun <- gather(edu_mun,categoria,observaciones,-c(`Código`,Municipio))
emp_dep <- gather(emp_dep,categoria,observaciones,-c(`Código`,Departamento))
emp_mun <- gather(emp_mun,categoria,observaciones,-c(`Código`,Municipio))
hog_dep <- gather(hog_dep,categoria,observaciones,-c(`Código`,Departamento))
hog_mun <- gather(hog_mun,categoria,observaciones,-c(`Código`,Municipio))
pob_dep <- gather(pob_dep,categoria,observaciones,-c(`Código`,Departamento))
pob_mun <- gather(pob_mun,categoria,observaciones,-c(`Código`,Municipio))
tec_dep <- gather(tec_dep,categoria,observaciones,-c(`Código`,Departamento))
tec_mun <- gather(tec_mun,categoria,observaciones,-c(`Código`,Municipio))
viv_dep <- gather(viv_dep,categoria,observaciones,-c(`Código`,Departamento))
viv_mun <- gather(viv_mun,categoria,observaciones,-c(`Código`,Municipio))
pue_dep <- gather(pue_dep,categoria,observaciones,-c(`Código`,Departamento))

#Separamos bien las tablas
car_dep <- split_outer_function(car_dep)
car_mun <- split_outer_function(car_mun)
edu_dep <- split_outer_function(edu_dep)
edu_mun <- split_outer_function(edu_mun)
emp_dep <- split_outer_function(emp_dep)
emp_mun <- split_outer_function(emp_mun)
hog_dep <- split_outer_function(hog_dep)
hog_mun <- split_outer_function(hog_mun)
pob_dep <- split_outer_function(pob_dep)
pob_mun <- split_outer_function(pob_mun)
tec_dep <- split_outer_function(tec_dep)
tec_mun <- split_outer_function(tec_mun)
viv_dep <- split_outer_function(viv_dep)
viv_mun <- split_outer_function(viv_mun)
pue_dep <- split_outer_function(pue_dep)

#Separar columna codigo en municipio
car_mun <- separate_id_outer(car_mun)
edu_mun <- separate_id_outer(edu_mun)
emp_mun <- separate_id_outer(emp_mun)
hog_mun <- separate_id_outer(hog_mun)
pob_mun <- separate_id_outer(pob_mun)
tec_mun <- separate_id_outer(tec_mun)
viv_mun <- separate_id_outer(viv_mun)

#Tabla departamentos
tabla_dep <- as.data.frame(unique(car_dep$`Código`), stringsAsFactors = FALSE)
tabla_dep$region <- apply(tabla_dep,1,define_region)
names(tabla_dep)[1] <- c("codigo_dep")
tabla_pob_region <- inner_join(tabla_dep, car_dep %>% filter(caracteristica == "Total de personas") %>% select(1,5), by = c("codigo_dep" = "Código")) %>% select(2,3) %>% group_by(region) %>% summarise(pob_total = sum(observaciones))
tabla_pob_region$porcentaje_total <- tabla_pob_region$pob_total/sum(tabla_pob_region$pob_total)
tabla_pob_region <- tabla_pob_region %>% select(1,3)

tabla_viv_region <- inner_join(tabla_dep, viv_dep %>% filter(caracteristica == "Total de viviendas") %>% select(1,5), by = c("codigo_dep" = "Código")) %>% select(2,3) %>% group_by(region) %>% summarise(viv_total = sum(observaciones))
tabla_viv_region$porcentaje_total <- tabla_viv_region$viv_total/sum(tabla_viv_region$viv_total)
tabla_viv_region <- tabla_viv_region %>% select(1,3)
```



#EDA
```{r, cache=TRUE}

plot_barcharts(car_dep)
plot_barcharts(edu_dep)
plot_barcharts(emp_dep)
plot_barcharts(pob_dep)
plot_barcharts(tec_dep)
plot_barcharts(pue_dep)
plot_barcharts_hog(hog_dep)
plot_barcharts_norm_viv(viv_dep)

```



#Corrplots
```{r, cache=TRUE}

split_corr_plot(tabla_correlaciones, splits = 4, split_size = 10)

```



#Exportar Tablas
```{r, cache=TRUE}

write.csv(car_dep,'caracteristicas_departamental_tidy.csv')
write.csv(car_mun,'caracteristicas_municipal_tidy.csv')
write.csv(edu_dep,'educacion_departamental_tidy.csv')
write.csv(edu_mun,'educacion_municipal_tidy.csv')
write.csv(emp_dep,'empleo_departamental_tidy.csv')
write.csv(emp_mun,'empleo_municipal_tidy.csv')
write.csv(hog_dep,'hogares_departamental_tidy.csv')
write.csv(hog_mun,'hogares_municipal_tidy.csv')
write.csv(pob_dep,'poblacion_departamental_tidy.csv')
write.csv(pob_mun,'poblacion_municipal_tidy.csv')
write.csv(tec_dep,'tecnologia_departamental_tidy.csv')
write.csv(tec_mun,'tecnologia_municipal_tidy.csv')
write.csv(viv_dep,'vivienda_departamental_tidy.csv')
write.csv(viv_mun,'vivienda_municipal_tidy.csv')
write.csv(pue_dep,'pueblo_departamental_tidy.csv')


```















