---
title: "Lab 2"
author: "Guillermo Puente"
date: "7 de agosto de 2019"
output: rmarkdown::github_document
---

```{r, cache=TRUE}
require(RMySQL)
connection_name <- "datawrangling.co4pgsadnasr.us-east-2.rds.amazonaws.com"
db_name <- "dataWrangling"
user <- "dstrack"
password <- "datawrangling2019"
drv = dbDriver("MySQL")
mydb = dbConnect(drv, host=connection_name, dbname=db_name, user=user, pass=password)
```

```{r}
dbListFields(mydb,"heroes_information")
dbGetQuery(mydb, "SELECT * FROM heroes_information")
dbGetQuery(mydb, "SELECT name, Publisher FROM heroes_information")
dbGetQuery(mydb, "SELECT DISTINCT Publisher FROM heroes_information")
dbGetQuery(mydb, "SELECT name, Publisher FROM heroes_information")
dbGetQuery(mydb, "SELECT COUNT(DISTINCT Publisher) FROM heroes_information")
dbGetQuery(mydb, "SELECT COUNT(DISTINCT Publisher) FROM heroes_information")
dbGetQuery(mydb, "SELECT * FROM heroes_information WHERE height > 200")
dbGetQuery(mydb, "SELECT * FROM heroes_information WHERE race = 'human' AND height >200")
dbGetQuery(mydb, "SELECT * FROM heroes_information WHERE Weight > 100 AND Weight < 200")
dbGetQuery(mydb, "SELECT COUNT * FROM heroes_information WHERE 'Eye color' = 'red' OR 'Eye color' = 'blue'")
dbGetQuery(mydb, "SELECT * FROM heroes_information WHERE weight BETWEEN 100 and 200")
dbGetQuery(mydb, "SELECT name, weight, height FROM heroes_information WHERE weight > 200 AND height > 100 ORDER BY height desc")
dbGetQuery(mydb, "SELECT name, race FROM heroes_information ORDER BY name, race")
dbGetQuery(mydb, "SELECT publisher, gender, COUNT(*) FROM heroes_information WHERE gender = 'female' GROUP BY publisher ORDER BY 3 desc")
dbGetQuery(mydb, "SELECT publisher, alignment, race, COUNT(*) FROM heroes_information WHERE aligment = 'good' GROUP BY publisher HAVING COUNT(*) > 30;")
```

